#!/bin/bash

borders width=6.0 \
        hidpi=on \
        active_color=0xff89b4fa \
        inactive_color=0x00000000 \
        background_color=0x302c2e34 \
        style=round \
        radius=12.0 \
        blur_radius=30 \
        active_opacity=1.0 \
        inactive_opacity=0.0
